### ISSUE TITLE
面包屑关闭，缓存没清理

### ISSUE THREAD

**Issue by xiaoBai516** [fuzui/RuoYi-Antdv#1]
![image](https://user-images.githubusercontent.com/50570625/117953534-ad36d080-b348-11eb-8066-eab7b6807c05.png)

**Comment by fuzui** [comment]
已修复。
[fix: 多页签重复以及缓存问题](https://github.com/fuzui/RuoYi-Antdv/commit/ad70932b42d88ad67ebccf74aab143f880b59382)
