### ISSUE TITLE
settingDrawer启动初始化报错

### ISSUE THREAD

**Issue by xiahuhu1** [fuzui/RuoYi-Antdv#3]
项目启动之后侧边栏主题设置的主题颜色和导航模式的值无法获取，Local Storage中没有缓存主题配置信息，只存储了token信息，请问这个问题如何排查呢？

![image](https://user-images.githubusercontent.com/38675377/148645924-23519e16-3f23-4d6e-9f14-16c06fabec39.png)

![image](https://user-images.githubusercontent.com/38675377/148646008-1dd33ac1-eaf6-4a0e-9efb-ba95c1f54820.png)

**Comment by fuzui** [comment]
有修改过代码吗

**Comment by fuzui** [comment]
未复现
