### ISSUE TITLE
多页签时--嵌套路由也打开了一个新的页签

### ISSUE THREAD

**Issue by zouteng** [fuzui/RuoYi-Antdv#4]
个人设置里：基本设置和安全设置能否只打开一个页签？
![图片](https://user-images.githubusercontent.com/3103285/149700498-52fd0c8b-4195-43fc-ba23-d045ff8df6e0.png)

**Comment by fuzui** [comment]
已调整。
[feat: 合并个人设置路由](https://github.com/fuzui/RuoYi-Antdv/commit/f1d08c91e0cf8685dcf2876045aac4f4b3b5affa)
